
spring:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/online-shop?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: online-shop-admin
    password: 1234abc

# by default the port of this app was 8080, to change it we add what follows:
server:
  port: 8085
